<?php

namespace Modules\Inventory\Entities;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\QueryException;
// Removed: use App\Traits\HasBranch;
use Modules\Inventory\Entities\InventoryItemCategory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use App\Models\MenuItem;
use App\Traits\HasRestaurant;
// use Modules\Inventory\Database\Factories\InventoryItemFactory;

class InventoryItem extends Model
{
    use HasFactory;
    use HasRestaurant;
    // Removed HasBranch trait - items are now restaurant-scoped

    /**
     * The attributes that are mass assignable.
     */
    protected $fillable = [
        // 'branch_id', - Removed - items shared across restaurant
        'restaurant_id',
        'name',
        'item_code',
        'inventory_item_category_id',
        'unit_id',
        'unit_purchase_price',
        'threshold_quantity',
        'preferred_supplier_id',
        'reorder_quantity',
        'is_active',
    ];

    protected $casts = [
        'is_active' => 'boolean',
    ];

    public function scopeActiveForPurchase($query)
    {
        return $query->where('is_active', true);
    }

    protected static function boot()
    {
        parent::boot();

        static::creating(function (self $model) {
            if (!$model->restaurant_id && restaurant()) {
                $model->restaurant_id = restaurant()->id;
            }
        });
    }



    public function category()
    {
        return $this->belongsTo(InventoryItemCategory::class, 'inventory_item_category_id');
    }

    public function unit()
    {
        return $this->belongsTo(Unit::class);
    }

    public function stocks(): HasMany
    {
        return $this->hasMany(InventoryStock::class);
    }

    public function movements(): HasMany
    {
        return $this->hasMany(InventoryMovement::class);
    }

    public function getCurrentStockAttribute()
    {
        return $this->stocks()->sum('quantity');
    }

    public function getStockStatus()
    {
        $currentStock = $this->current_stock;

        if ($currentStock <= 0) {
            return [
                'status' => 'Out of Stock',
                'class' => 'bg-red-100 dark:bg-red-900 text-red-800 dark:text-red-200'
            ];
        } elseif ($currentStock <= $this->threshold_quantity) {
            return [
                'status' => 'Low Stock',
                'class' => 'bg-yellow-100 dark:bg-yellow-900 text-yellow-800 dark:text-yellow-200'
            ];
        }

        return [
            'status' => 'In Stock',
            'class' => 'bg-green-100 dark:bg-green-900 text-green-800 dark:text-green-200'
        ];
    }

    public function menuItems(): BelongsToMany
    {
        return $this->belongsToMany(MenuItem::class, 'recipes', 'inventory_item_id', 'menu_item_id');
    }

    public function supplier(): BelongsTo
    {
        return $this->belongsTo(Supplier::class, 'preferred_supplier_id');
    }

    /* ------------------------------------------------------------------ */
    /*  Item Code Auto-generation                                          */
    /* ------------------------------------------------------------------ */

    /**
     * Prefix used for auto-generated inventory item codes.
     */
    public const ITEM_CODE_PREFIX = 'INV';

    /**
     * Largest numeric suffix among strict auto-generated codes (PREFIX + digits)
     * for the given restaurant. Used to pick the next sequence number.
     */
    public static function maxAutoGeneratedItemCodeSuffixForRestaurant(int $restaurantId): int
    {
        $prefix = self::ITEM_CODE_PREFIX;
        $prefixLen = strlen($prefix) + 1;
        $driver = static::query()->getConnection()->getDriverName();

        if (in_array($driver, ['mysql', 'mariadb'], true)) {
            return (int) static::query()
                ->where('restaurant_id', $restaurantId)
                ->whereRaw('item_code REGEXP ?', ['^' . $prefix . '[0-9]+$'])
                ->selectRaw('COALESCE(MAX(CAST(SUBSTRING(item_code, ?) AS UNSIGNED)), 0) as suffix_max', [$prefixLen])
                ->value('suffix_max');
        }

        if ($driver === 'pgsql') {
            return (int) static::query()
                ->where('restaurant_id', $restaurantId)
                ->whereRaw('item_code ~ ?', ['^' . $prefix . '[0-9]+$'])
                ->selectRaw('COALESCE(MAX(CAST(SUBSTRING(item_code FROM ?) AS INTEGER)), 0) as suffix_max', [$prefixLen])
                ->value('suffix_max');
        }

        $max = 0;
        static::query()
            ->where('restaurant_id', $restaurantId)
            ->where('item_code', 'like', $prefix . '%')
            ->pluck('item_code')
            ->each(function ($code) use (&$max, $prefix) {
                if (preg_match('/^' . preg_quote($prefix, '/') . '(\d+)$/', (string) $code, $m)) {
                    $max = max($max, (int) $m[1]);
                }
            });

        return $max;
    }

    /**
     * Format a numeric sequence as PREFIX + zero-padded digits (minimum width 4).
     * Examples: 1 -> INV0001, 9999 -> INV9999, 12345 -> INV12345.
     */
    public static function formatAutoItemCode(int $numericSuffix): string
    {
        $s = (string) $numericSuffix;
        $padLen = max(4, strlen($s));

        return self::ITEM_CODE_PREFIX . str_pad($s, $padLen, '0', STR_PAD_LEFT);
    }

    /**
     * Next auto item code for the given restaurant.
     * Concurrent callers may get the same candidate until insert; use
     * {@see isDuplicateRestaurantItemCodeException} and retry on create.
     */
    public static function generateNextItemCodeForRestaurant(int $restaurantId): string
    {
        $next = static::maxAutoGeneratedItemCodeSuffixForRestaurant($restaurantId) + 1;

        return static::formatAutoItemCode($next);
    }

    /**
     * True when the exception is a duplicate-key violation on
     * (restaurant_id, item_code) / item_code.
     */
    public static function isDuplicateRestaurantItemCodeException(QueryException $e): bool
    {
        $msg = strtolower($e->getMessage());
        $sqlState = $e->errorInfo[0] ?? '';

        $isIntegrity = in_array($sqlState, ['23000', '23505'], true);
        if (!$isIntegrity) {
            return false;
        }

        $driverCode = isset($e->errorInfo[1]) ? (int) $e->errorInfo[1] : 0;
        $looksDuplicate = in_array($driverCode, [1062, 19], true)
            || str_contains($msg, 'unique')
            || str_contains($msg, 'duplicate');

        if (!$looksDuplicate) {
            return false;
        }

        return str_contains($msg, 'item_code')
            || str_contains($msg, 'inventory_items_restaurant_item_code_unique');
    }
}
