<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Modules\Inventory\Entities\InventoryItem;

/**
 * Backfills item_code for existing inventory_items per restaurant using the
 * standard `INV` + zero-padded suffix format (e.g. INV0001).
 */
return new class extends Migration
{
    public function up(): void
    {
        if (!Schema::hasColumn('inventory_items', 'item_code')) {
            return;
        }

        $restaurantIds = DB::table('inventory_items')
            ->whereNotNull('restaurant_id')
            ->whereNull('item_code')
            ->distinct()
            ->pluck('restaurant_id');

        foreach ($restaurantIds as $restaurantId) {
            $next = InventoryItem::maxAutoGeneratedItemCodeSuffixForRestaurant((int) $restaurantId) + 1;

            $items = DB::table('inventory_items')
                ->where('restaurant_id', $restaurantId)
                ->whereNull('item_code')
                ->orderBy('id')
                ->get(['id']);

            foreach ($items as $item) {
                $code = InventoryItem::formatAutoItemCode($next);

                // Defensive collision check (in case some rows had partial codes).
                $exists = DB::table('inventory_items')
                    ->where('restaurant_id', $restaurantId)
                    ->where('item_code', $code)
                    ->exists();

                while ($exists) {
                    $next++;
                    $code = InventoryItem::formatAutoItemCode($next);
                    $exists = DB::table('inventory_items')
                        ->where('restaurant_id', $restaurantId)
                        ->where('item_code', $code)
                        ->exists();
                }

                DB::table('inventory_items')
                    ->where('id', $item->id)
                    ->update(['item_code' => $code]);

                $next++;
            }
        }
    }

    public function down(): void
    {
        // Intentionally non-destructive: keep the codes if rolled back so the
        // values do not vanish from related views. Re-running up() is a no-op
        // for rows that already have a code.
    }
};
